name: test_deploy

on: push

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # Run linting. This example uses the Maven Checkstyle plugin.
      # Ensure your pom.xml configures checkstyle if you use this step.
      - name: Lint Code with Checkstyle
        run: mvn checkstyle:check

  test:
    needs: lint
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Run Tests
        run: mvn test

  deploy:
    needs: test
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # Build the Spring Boot application (skipping tests because they've already run)
      - name: Build Application
        run: mvn clean package -DskipTests

      # Deployment step (update this with your actual deployment commands)
      - name: Deploy Application
        run: echo "Deploying application... (insert your deployment commands here)"
